In [11]:
#!pip install numpy
import numpy as np 

import pandas as pd


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\beatr\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [8]:
matriz = np.array([[[1,5,9],[2,4,7],[2,0,7],[2,4,1]],[[1,5,9],[2,4,7],[2,0,7],[2,4,1]]])
matriz
matriz.shape


(2, 4, 3)

In [12]:
np.full((2,3), 25, int)

array([[25, 25, 25],
       [25, 25, 25]])

In [16]:
matriz = np.random.randint(1,10,(5,5))
print(matriz)

[[3 1 3 7 1]
 [8 3 3 1 1]
 [6 7 8 4 6]
 [7 1 9 6 2]
 [3 4 8 5 7]]


In [18]:
matriz.std()

2.5935304123915723

In [21]:
pd.DataFrame(matriz)

0  1  2  3  4
0  3  1  3  7  1
1  8  3  3  1  1
2  6  7  8  4  6
3  7  1  9  6  2
4  3  4  8  5  7

In [23]:
pd.DataFrame(matriz,columns=["dia","mês","ano","seg","min"],index=["juliano","angelica","patricia","davi","vanessa"])

dia  mês  ano  seg  min
juliano     3    1    3    7    1
angelica    8    3    3    1    1
patricia    6    7    8    4    6
davi        7    1    9    6    2
vanessa     3    4    8    5    7

In [51]:
# 1. Crie um array NumPy com 10 elementos inteiros aleatórios no intervalo [0, 100] e exiba os valores e o tipo de dado do array.

np.random.randint(0,100,(10))


array([70, 55, 45, 73, 95, 88, 41, 74, 96, 21])

In [50]:
# 2. Crie uma matriz de 5x5 com valores aleatórios de [0,1) e encontre o valor mínimo, máximo e a média da matriz.

array2 = np.random.rand(5,5)
media = array2.mean()
media

0.598007439709919

In [49]:
#3. Crie um array com 10 elementos aleatórios no intervalo [0, 1). Em seguida, crie um novo array com os elementos do primeiro array multiplicados por 10 e convertidos para inteiro.

array3 = np.random.rand(10)*10
array3 = array3.astype(int)
array3

array([0, 4, 0, 4, 0, 0, 3, 5, 5, 4])

In [43]:
#4. Crie um array de duas dimensões com shape (3, 3) e valores aleatórios inteiros no intervalo [0, 9]. Substitua todos os elementos da segunda linha por -1.

array4 = np.random.randint(0,9,(3,3))
array4[1,:]= -1
array4

array([[ 8,  5,  2],
       [-1, -1, -1],
       [ 3,  8,  3]])

In [46]:
# 5. Crie um DataFrame com as seguintes informações:

pd.DataFrame({"Fruta":("Banana","Maçã","Pera"),"Preço":(7.90,10.20,11.80),"Quantidade":(12,3,4)})


Fruta  Preço  Quantidade
0  Banana    7.9          12
1    Maçã   10.2           3
2    Pera   11.8           4